addiction/models/base.py
from addiction.extensions import db


class BaseModel(db.Model):

    __abstract__ = True

    def create(self, commit=True):
        db.session.add(self)
        if commit:
            self.save()
        else:
            db.session.flush()

    @staticmethod
    def save():
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        self.save()

addiction/views/main/routes.py
from flask import Blueprint, render_template

from addiction.models import Project, Staff, HomePageText, PublicationCategory

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route("/")
def index():
    texts = HomePageText.get_texts_categorized()
    return render_template("main/index.html", texts=texts)


@main_blueprint.route("/projects")
def projects():
    finished_projects = Project.query.filter_by(is_finished=True).all()
    unfinished_projects = Project.query.filter_by(is_finished=False).all()
    return render_template("main/projects.html", unfinished_projects=unfinished_projects, finished_projects=finished_projects)


@main_blueprint.route("/about_us")
def about():
    staff_members = Staff.query.all()
    return render_template("main/about_us.html", staff_members=staff_members)


@main_blueprint.route("/resources")
def resources():
    categories = PublicationCategory.query.all()
    return render_template("main/resources.html", categories=categories)

addiction/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Addictions Studies</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/css/global.css') }}"/>
</head>
<body>
<div class="container" style="width:100%">
    {% include "layouts/navbar.html" %}

    {% block body %}
    {% endblock %}

    {% include "layouts/footer.html" %}

</div>

<script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

addiction/templates/layouts/footer.html
<footer>
    <div class="mail-box">
        <img src="{{ url_for('static', filename='images/icons/01-mail.svg') }}"
             class="mailLogo1"
             alt="Mail icon"/>
        <p class="mail">addictology@iliauni.edu.ge</p>
    </div>
    <p class="address">
        ქაქუცა ჩოლოყაშვილის გამზირი 3-5, ილიაუნის ე კორპუსი, ოთახი ე-238
    </p>
    <div class="icons-box">
        <a href="https://www.facebook.com/WordPress/" target="_blank">
            <img src="{{ url_for('static', filename='images/icons/facebook.svg') }}"
                 class="fbLogo img-fixed"
                 alt="Facebook icon"/>
        </a>
        <a href="mailto:addictology@iliauni.edu.ge">
            <img src="{{ url_for('static', filename='images/icons/02-mail.svg') }}"
                 class="mailLogo2"
                 alt="Mail icon"/>
        </a>
    </div>
    <p class="sub-text">
        საიტი შექმნილია ილიაუნის კიბერლაბორატორია
        <a href="http://unilab.iliauni.edu.ge/" target="_blank">უნილაბის</a>
        გუნდის მიერ
    </p>
</footer>

addiction/templates/layouts/navbar.html
{% from 'macros.html' import is_active %}

<header {% if request and request.endpoint != "main.index" %} class="border" {% endif %}>
    <div class="header-title-box">
        <h2>ადიქტოლოგიის ინსტიტუტი</h2>
        <p>
            ილიას სახელმწიფო უნივერსიტეტის ტომაშ ზაბრანსკის სახელობის
            ადიქტოლოგიის ინსტიტუტი
        </p>
    </div>
    <nav class="header-nav">
        <ul class="header-nav-box">
            <li><a href="{{ url_for('main.index') }}" class="{{ is_active('main.index') }}">მთავარი</a></li>
            <li><a href="{{ url_for('main.projects') }}" class="{{ is_active('main.projects') }}">პროექტები</a></li>
            <li><a href="{{ url_for('main.resources') }}" class="{{ is_active('main.resources') }}">რესურსები</a></li>
            <li><a href="{{ url_for('main.about') }}" class="{{ is_active('main.about') }}">ჩვენ შესახებ</a></li>
        </ul>
    </nav>

    <button class="btn-mobile-nav">
        <img src="{{ url_for('static', filename='images/icons/menu.svg') }}" alt="Menu Icon"
             class="icon-mobile-nav menu"/>
        <img src="{{ url_for('static', filename='images/icons/close.svg') }}" alt="Close Icon"
             class="icon-mobile-nav close"/>
    </button>
</header>