addiction/models/projects.py
from addiction.extensions import db
from addiction.models.base import BaseModel


class Project(BaseModel):
    __tablename__ = 'projects'

    id = db.Column(db.Integer, primary_key=True)
    year = db.Column(db.String)
    title = db.Column(db.String)
    description = db.Column(db.String)
    is_finished = db.Column(db.Boolean)

addiction/views/main/routes.py
from flask import Blueprint, render_template

from addiction.models import Project, Staff, HomePageText, PublicationCategory

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route("/")
def index():
    texts = HomePageText.get_texts_categorized()
    return render_template("main/index.html", texts=texts)


@main_blueprint.route("/projects")
def projects():
    finished_projects = Project.query.filter_by(is_finished=True).all()
    unfinished_projects = Project.query.filter_by(is_finished=False).all()
    return render_template("main/projects.html", unfinished_projects=unfinished_projects, finished_projects=finished_projects)


@main_blueprint.route("/about_us")
def about():
    staff_members = Staff.query.all()
    return render_template("main/about_us.html", staff_members=staff_members)


@main_blueprint.route("/resources")
def resources():
    categories = PublicationCategory.query.all()
    return render_template("main/resources.html", categories=categories)

addiction/views/publications/routes.py
from flask import Blueprint, render_template

from addiction.models import Publication

publication_blueprint = Blueprint('publications', __name__)


@publication_blueprint.route("/publications/<int:category_id>")
def publication(category_id):
    publications = Publication.query.filter_by(category_id=category_id).all()
    return render_template("publications/publications.html", publications=publications)

addiction/templates/main/about_us.html
{% extends "layouts/base.html" %}

{% block body %}

    <main>
        <div class="main-container">
            <div class="main-box">
                <h2 class="main-box-subtitle">ჩვენ შესახებ</h2>
                <div class="main-box-line"></div>
                <div class="main-box-texts">
                    {% for member in staff_members %}
                        <div class="main-box-texts-el">
                            <p>
                                <span>{{ member.name }},</span>
                                {{ member.position }}
                                <br>
                                საკონტაქტო ინფორმაცია
                                <a href="mailto:{{ member.email }}">{{ member.email }}</a>
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>

{% endblock %}

addiction/templates/main/index.html
{% extends "layouts/base.html" %}

{% block body %}
    <main>
        <div class="main-container">
            <img src="{{ url_for('static', filename='images/01-main.png') }}" alt=""/>
            <div class="main-box">
                <h2 class="main-box-subtitle">ინსტიტუტის შესახებ</h2>
                <div class="main-box-line"></div>
                <div class="main-box-texts">
                    {% for text in texts["about_institute"] %}
                        <div class="main-box-texts-el">
                            <p>
                                <span colon=":">{{ text.name }}</span>
                                {{ text.text }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="main-container">
            <img src="{{ url_for('static', filename='images/02-main.png') }}" alt=""/>
            <div class="main-box">
                <h2 class="main-box-subtitle">მუშაობის მიმართულებები</h2>
                <div class="main-box-line"></div>
                <div class="main-box-texts">
                    {% for text in texts["work_directions"] %}
                        <div class="main-box-texts-el">
                            <p>
                                <span>{{ text.name }}</span>
                                {{ text.text }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="main-container">
            <img src="{{ url_for('static', filename='images/03-main.png') }}" alt=""/>
            <div class="main-box">
                <h2 class="main-box-subtitle">ინსტიტუტის შექმნის ისტორია</h2>
                <div class="main-box-line"></div>
                <div class="main-box-texts">
                    {% for text in texts["institute_history"] %}
                        <div class="main-box-texts-el">
                            <p>
                                {{ text.text }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

addiction/templates/main/projects.html
{% extends "layouts/base.html" %}

{% block body %}
    <main>
        <div class="main-container">
            <div class="main-box">
                <h2 class="main-box-subtitle">მიმდინარე პროექტები</h2>
                <div class="main-box-line"></div>
                <div class="main-box-texts">
                    {% for project in unfinished_projects %}
                        <div class="main-box-texts-el">
                            <p>
                                <span> {{ project.year }} - {{ project.title }}</span>
                                <br>
                                {{ project.description }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="main-container">
            <div class="main-box">
                <h2 class="main-box-subtitle">განხორციელებული პროექტები</h2>
                <div class="main-box-line"></div>
                <div class="main-box-texts">
                    {% for project in finished_projects %}
                        <div class="main-box-texts-el">
                            <p>
                                <span> {{ project.year }} - {{ project.title }}</span>
                                <br>
                                {{ project.description }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>

{% endblock %}

addiction/templates/main/resources.html
{% extends "layouts/base.html" %}

{% block body %}

    <main>
        <div class="main-container">
            <div class="main-box">
                <h2 class="main-box-subtitle">რესურსები</h2>
                <div class="main-box-line"></div>
                <div class="main-box-texts">
                    <div class="main-box-texts-el">
                        <p>
                            ილიას სახელმწიფო უნივერსიტეტის ტომაშ ზაბრანსკის სახელობის
                            ადიქტოლოგიის ინსტიტუტის პუბლიკაციები კატეგორიების მიხედვით:
                        </p>
                    </div>
                    <div class="main-box-texts-el">
                        <ul>
                            {% for category in categories %}
                                <li>
                                    <a href="{{ url_for('publications.publication', category_id=category.id) }}">
                                        {{ category.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}